development:
  adapter: postgresql
  encoding: unicode
  database: chat_development
  pool: 5
  username: chat
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: chat_test
  pool: 5
  username: chat
  password: password1